version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: creative_distribution_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: creative
    ports:
      - "5432:5432"
    volumes:
      - creative_distribution_db:/var/lib/postgresql/data
    networks:
      - postgres_network

volumes:
  creative_distribution_db:

networks:
  postgres_network:
    driver: bridge